### PR TITLE
Feature: Dynamic README generation for downloads

### PR DESCRIPTION
**Pull request by ppmathis**
This PR introduces a dynamically generated README which contains links to all Pi4J library archives, instructions on how to setup the APT/PPA repository as well as download links to the OS image flavors maintained as part of the `pi4j-os` repository.

I initially thought that we could trigger this action both on `workflow_dispatch` (to be triggered by `pi4j-os` when a new release happens) as well as `push` to auto-commit whenever a `*.zip` file gets uploaded, but this might conflict with the existing `rebuild-repo` CI task as both of them try to push a commit and would be triggered in parallel. Merging both workflows into one would also be problematic though, as then we'd also rebuild the Debian repository when just `*.zip` gets built or the README template changes.

I would suggest that we keep this workflow as `workflow_dispatch`-only and trigger it with a GitHub PAT (personal access token) both from `rebuild-repo.yml` in this repo (as `*.deb` and `*.zip` are always pushed at the same time, correct?) and the `pi4j-os` repository whenever a release happens.

Does that work or do you have any other idea for this? Also, is there already such a PAT which could be used?

The README generation itself is complete already and an example can be found as part of the commit 41ca20e or by visiting the [feat/dynamic-readme](https://github.com/Pi4J/download/tree/feat/dynamic-readme) branch.

### CODE REVIEW

**Comment by FDelporte** [comment]
I'm don't know of such a PAT, what should I check for this?

**Comment by ppmathis** [comment]
> I'm don't know of such a PAT, what should I check for this?

GitHub does not support organisation-based tokens, so a member of the Pi4J team with sufficient privileges would have to create a personal access token underneath https://github.com/settings/tokens with the appropriate scope to trigger a workflow in another repository.

I see a reference to a secret `API_TOKEN_GITHUB` within https://github.com/Pi4J/pi4j-v2/blob/develop/.github/workflows/release.yml which might point to some PAT, but the person who configured that probably knows most about this - so maybe @savageautomate can solve the mystery here, given that he has been the only person to touch this file so far :)

**Comment by ppmathis** [comment]
@FDelporte @savageautomate I think this is ready for review now, this PR basically introduces a new GitHub Actions workflow which can only be triggered via `workflow_dispatch` (an action that an user can do by messing around with the UI, but also via the API).

This new workflow `dynamic-readme.yml` will checkout the repository, generate a JSON list of all files in the repository using `jq` (preinstalled on GitHub Actions) and then uses `gomplate` to dynamically render the README based on a template. This will also fetch some JSON data from `https://pi4j-download.com/versions.php` which provides information about the OS images stored on our repository mirror. After rendering the README, it gets automatically committed and pushed to the repository.

I also took the liberty to change the commit author to `Pi4J Bot` with the bot-mail address, so future automated commits to this repository will automatically be linked to the bot account. Please let me know should you instead prefer to keep it as team-address, which does not link to any GitHub user.

After this PR has been merged and the feature is available in the `main` branch, I will submit a follow-up PR which adds a single additional step to the end of `rebuild-repo.yml` (previously just `build.yml`, used for rebuilding the Debian repository) for triggering the `dynamic-readme` workflow via API.

Additionally, another PR will land in the `Pi4J/pi4j-os` repository to automatically trigger this workflow on every snapshot or tagged release. That way this README should always be up-to-date and contain information about the last Pi4J releases.

**Review by eitch — APPROVED** [review]

**Comment by eitch** [comment]
@FDelporte these changes seem good, what do you think?

**Review by FDelporte — APPROVED** [review]
As always, very nice work. You keep impressing me with the quality of code and chosen approach. The team address is not intended for this kind of message, so bot@ is the way forward! Many thanks!

**Pull request merged**
